import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        갑: "url('/images/bg/갑.png')",
        을: "url('/images/bg/을.png')",
        병: "url('/images/bg/병.png')",
        정: "url('/images/bg/정.png')",
        무: "url('/images/bg/무.png')",
        기: "url('/images/bg/기.png')",
        경: "url('/images/bg/경.png')",
        신: "url('/images/bg/신.png')",
        임: "url('/images/bg/임.png')",
        계: "url('/images/bg/계.png')",
        갑술: "url('/images/fruits/갑술.png')",
        갑신: "url('/images/fruits/갑신.png')",
        갑오: "url('/images/fruits/갑오.png')",
        갑인: "url('/images/fruits/갑인.png')",
        갑자: "url('/images/fruits/갑자.png')",
        갑진: "url('/images/fruits/갑진.png')",
        을묘: "url('/images/fruits/을묘.png')",
        을미: "url('/images/fruits/을미.png')",
        을사: "url('/images/fruits/을사.png')",
        을유: "url('/images/fruits/을유.png')",
        을축: "url('/images/fruits/을축.png')",
        을해: "url('/images/fruits/을해.png')",
        병술: "url('/images/fruits/병술.png')",
        병신: "url('/images/fruits/병신.png')",
        병오: "url('/images/fruits/병오.png')",
        병인: "url('/images/fruits/병인.png')",
        병자: "url('/images/fruits/병자.png')",
        병진: "url('/images/fruits/병진.png')",
        정묘: "url('/images/fruits/정묘.png')",
        정미: "url('/images/fruits/정미.png')",
        정사: "url('/images/fruits/정사.png')",
        정유: "url('/images/fruits/정유.png')",
        정축: "url('/images/fruits/정축.png')",
        정해: "url('/images/fruits/정해.png')",
        무술: "url('/images/fruits/무술.png')",
        무신: "url('/images/fruits/무신.png')",
        무오: "url('/images/fruits/무오.png')",
        무인: "url('/images/fruits/무인.png')",
        무자: "url('/images/fruits/무자.png')",
        무진: "url('/images/fruits/무진.png')",
        기묘: "url('/images/fruits/기묘.png')",
        기미: "url('/images/fruits/기미.png')",
        기사: "url('/images/fruits/기사.png')",
        기유: "url('/images/fruits/기유.png')",
        기축: "url('/images/fruits/기축.png')",
        기해: "url('/images/fruits/기해.png')",
        경술: "url('/images/fruits/경술.png')",
        경신: "url('/images/fruits/경신.png')",
        경오: "url('/images/fruits/경오.png')",
        경인: "url('/images/fruits/경인.png')",
        경자: "url('/images/fruits/경자.png')",
        경진: "url('/images/fruits/경진.png')",
        신묘: "url('/images/fruits/신묘.png')",
        신미: "url('/images/fruits/신미.png')",
        신사: "url('/images/fruits/신사.png')",
        신유: "url('/images/fruits/신유.png')",
        신축: "url('/images/fruits/신축.png')",
        신해: "url('/images/fruits/신해.png')",
        임술: "url('/images/fruits/임술.png')",
        임신: "url('/images/fruits/임신.png')",
        임오: "url('/images/fruits/임오.png')",
        임인: "url('/images/fruits/임인.png')",
        임자: "url('/images/fruits/임자.png')",
        임진: "url('/images/fruits/임진.png')",
        계묘: "url('/images/fruits/계묘.png')",
        계미: "url('/images/fruits/계미.png')",
        계사: "url('/images/fruits/계사.png')",
        계유: "url('/images/fruits/계유.png')",
        계축: "url('/images/fruits/계축.png')",
        계해: "url('/images/fruits/계해.png')",
      },
      colors: {
        'Dark-Brown': '#2B1E08',
        brown: '#453311',
        Gray: '#C2C2C2',
        Beige: '#FDFAF5',
        'Secondary-Green': '#C2E679',
        'Secondary-Red': '#F69877',
        'Secondary-Hollow-Red': '#FDEAE3',
        'Secondary-Yellow': '#F9DE78',
        'Secondary-Blue': '#97B3DA',
        'Secondary-Grpae': '#BAB4D2',
        'Secondary-Melon': '#C1E37E',
        'Secondary-Hollow-Melon': '#F3F9E4',
        'Secondary-Purple': '##BAB4D2',
        'Background-Beige1': '#FDFAF5',
        'Background-Beige2': '#FBF4EA',
        'Background-Beige3': '#F9EFE1',
      },
      screens: {
        sm: '375px',
        md: '600px',
      },
    },
  },
  plugins: [],
}
export default config
